name: TarpitPlugin
version: 1.0.0
main: com.nixietab.tarpitplugin.TarpitPlugin
api-version: 1.13
description: A plugin that implements tarpit functionality for non-whitelisted players
author: NixieTab